import type { EncounterDefinition } from '../domain/types';

export const encounters = [
  {
    id: 'enc_tutorial',
    name: '港都防衛演習',
    kind: 'tutorial',
    victoryFlag: 'flag_tutorial_victory',
    enemies: [
      {
        id: 'enm_01_port_raider',
        name: '港區襲擊者',
        element: 'wind',
        maxHp: 1800,
        attack: 180,
        modeGauge: 0,
        actions: [{ id: 'raider-strike', name: '突擊', power: 100, target: 'single', telegraphed: false }],
      },
      {
        id: 'enm_02_tide_drone',
        name: '潮汐無人機',
        element: 'earth',
        maxHp: 2200,
        attack: 160,
        modeGauge: 0,
        actions: [{ id: 'drone-burst', name: '散射', power: 85, target: 'all', telegraphed: false }],
      },
    ],
  },
  {
    id: 'enc_surface_ruins',
    name: '地表遺跡勘查',
    kind: 'normal',
    victoryFlag: 'flag_surface_ruins_victory',
    enemies: [
      {
        id: 'enm_02_tide_drone',
        name: '潮汐無人機',
        element: 'earth',
        maxHp: 3000,
        attack: 210,
        modeGauge: 0,
        actions: [{ id: 'ruin-scan-burst', name: '掃描散射', power: 95, target: 'all', telegraphed: false }],
      },
      {
        id: 'enm_03_ruin_guardian',
        name: '遺跡守衛',
        element: 'earth',
        maxHp: 4600,
        attack: 260,
        modeGauge: 0,
        actions: [
          { id: 'guardian-hammer', name: '地脈重擊', power: 125, target: 'single', telegraphed: false },
          { id: 'guardian-pulse', name: '遺跡脈衝', power: 105, target: 'all', telegraphed: true },
        ],
      },
    ],
  },
  {
    id: 'enc_orbital_outpost',
    name: '軌道升降機前哨',
    kind: 'normal',
    victoryFlag: 'flag_orbital_outpost_victory',
    enemies: [
      {
        id: 'enm_01_port_raider',
        name: '升降機襲擊者',
        element: 'wind',
        maxHp: 3300,
        attack: 250,
        modeGauge: 0,
        actions: [{ id: 'outpost-strike', name: '高架突擊', power: 115, target: 'single', telegraphed: false }],
      },
      {
        id: 'enm_02_tide_drone',
        name: '前哨無人機',
        element: 'earth',
        maxHp: 3500,
        attack: 230,
        modeGauge: 0,
        actions: [{ id: 'outpost-burst', name: '軌道散射', power: 100, target: 'all', telegraphed: false }],
      },
      {
        id: 'enm_03_ruin_guardian',
        name: '前哨遺跡守衛',
        element: 'earth',
        maxHp: 5600,
        attack: 290,
        modeGauge: 0,
        actions: [{ id: 'outpost-pulse', name: '封鎖脈衝', power: 120, target: 'all', telegraphed: true }],
      },
    ],
  },
  {
    id: 'enc_leyline_core',
    name: '沉睡地脈核心',
    kind: 'boss',
    victoryFlag: 'flag_leyline_core_victory',
    enemies: [
      {
        id: 'enm_03_ruin_guardian',
        name: '地脈核心守衛',
        element: 'earth',
        maxHp: 14000,
        attack: 340,
        modeGauge: 100,
        actions: [
          { id: 'core-crush', name: '核心重壓', power: 130, target: 'single', telegraphed: false },
          { id: 'leyline-eruption', name: '地脈噴發', power: 145, target: 'all', telegraphed: true },
          { id: 'ancient-lock', name: '古代封鎖', power: 105, target: 'all', telegraphed: true, statusId: 'ancient-lock' },
        ],
      },
    ],
  },
  {
    id: 'enc_tidal_boss',
    name: '潮汐守望者',
    kind: 'boss',
    victoryFlag: 'flag_tidal_boss_victory',
    enemies: [
      {
        id: 'boss_01_tidal_watchkeeper',
        name: '潮汐守望者',
        element: 'dark',
        maxHp: 18000,
        attack: 360,
        modeGauge: 100,
        actions: [
          { id: 'pressure-claw', name: '壓力鉗擊', power: 120, target: 'single', telegraphed: false },
          { id: 'tidal-impact', name: '全體潮汐衝擊', power: 150, target: 'all', telegraphed: true },
          { id: 'depth-corrosion', name: '深潮侵蝕', power: 90, target: 'all', telegraphed: true, statusId: 'depth-corrosion' },
        ],
      },
    ],
  },
] as const satisfies readonly EncounterDefinition[];
